language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"
- "3.7"

stages:
- test_install
- test

jobs:
  include:
  - stage: test_install
    name: "Test pip installation"
    script:
    - "pip install ."
    - "python -c 'from thorlabs_mtd415t import *; print(__version__)'"

  - stage: test
    name: "Run unit tests"
    script:
    - "pip install -r requirements/dev.txt"
    - "pip install -e . && py.test -q --cov=thorlabs_mtd415t tests/"
