language: python
python:
- "2.7"
- "3.5"
- "3.6"
- "3.7"
- "3.8"
- "3.9"

script:
- "python --version"
- "pip install ."
- "python -c 'from thorlabs_mtd415t import *; print(__version__)'"
- "pip install -r requirements/dev.txt"
- "pip install -e . && py.test -q --cov=thorlabs_mtd415t tests/"
